-- ========================================================
-- 1. TABLA SUCURSALES
-- ========================================================
CREATE TABLE sucursales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================================================
-- 2. TABLA BARBEROS
-- ========================================================
CREATE TABLE barberos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    sucursal_id BIGINT REFERENCES sucursales(id) ON DELETE SET NULL,
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================================================
-- 3. TABLA SERVICIOS
-- ========================================================
CREATE TABLE servicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    duracion_minutos INT DEFAULT 30,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================================================
-- 4. TABLA TURNOS
-- ========================================================
CREATE TABLE turnos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_nombre VARCHAR(100) NOT NULL,
    cliente_telefono VARCHAR(50) NOT NULL,
    sucursal_id BIGINT REFERENCES sucursales(id) ON DELETE RESTRICT,
    barbero_id BIGINT REFERENCES barberos(id) ON DELETE RESTRICT,
    servicio_id BIGINT REFERENCES servicios(id) ON DELETE RESTRICT,
    fecha_hora TIMESTAMP WITH TIME ZONE NOT NULL,
    estado VARCHAR(50) DEFAULT 'confirmado',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ========================================================
-- RLS (MODO DESARROLLO)
-- ========================================================
ALTER TABLE sucursales ENABLE ROW LEVEL SECURITY;
ALTER TABLE barberos ENABLE ROW LEVEL SECURITY;
ALTER TABLE servicios ENABLE ROW LEVEL SECURITY;
ALTER TABLE turnos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acceso total a sucursales" ON sucursales FOR ALL USING (true);
CREATE POLICY "Acceso total a barberos" ON barberos FOR ALL USING (true);
CREATE POLICY "Acceso total a servicios" ON servicios FOR ALL USING (true);
CREATE POLICY "Acceso total a turnos" ON turnos FOR ALL USING (true);